### Accessing, Creating, Deleting, and Inserting Elements into ndarrays

In [2]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [5]:
print("first", x[0])

first 1


In [7]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [13]:
x = np.arange(1,10).reshape(3,3)


In [14]:
# We print X
print()
print('X = \n', x)
print()

# Let's access some elements in X
print('This is (0,0) Element in X:', x[0,0])
print('This is (0,1) Element in X:', x[0,1])
print('This is (2,2) Element in X:', x[2,2])


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [15]:
x = np.array([1,2,3,4,5])
print(x)

x = np.delete(x, [0,4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [23]:
box = np.arange(1,10).reshape(3,3)
print(box)

x = np.delete(box, [2], axis=0)
print("\n",x)

y = np.delete(box, [0,2], axis=1)
print("\n", y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]]

 [[2]
 [5]
 [8]]


In [24]:
x = np.array([1,2,3,4,5])
print(x)

x = np.append(x, [0,4])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 0 4]


In [35]:
box = np.arange(1,10).reshape(3,3)
print(box)

x = np.append(box, [[2,2,2]], axis=0)
print("\n",x)

y = np.append(box, [[0],[2],[3]], axis=1)
print("\n", y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 2 2]]

 [[1 2 3 0]
 [4 5 6 2]
 [7 8 9 3]]


In [58]:
x = np.array([1,2,5,6,7])
print(x)

x = np.insert(x, 2, [3,4])
print(x)

[1 2 5 6 7]
[1 2 3 4 5 6 7]


In [72]:
x = np.array([[1, 2, 3], [7, 8, 9]])
print(x)

x = np.insert(x, 1, [4,5,6], axis=0)
print("\n", x)

x = np.insert(x, [0, 3], 0, axis=1)
x = np.insert(x, [0, 3], 0, axis=0)
print("\n", x)

[[1 2 3]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [73]:
x = np.array([1,2])
print(x)

[1 2]


In [74]:
y = np.array([[3,4],[5,6]])
print(y)

[[3 4]
 [5 6]]


In [76]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [79]:
w = np.hstack((y, x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]
