In [3]:
import numpy as np

x = np.array([1 ,2 ,3 ,4 ,5 ])

In [4]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
x.dtype

dtype('int64')

In [6]:
x.shape

(5,)

In [7]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
Y.shape

(4, 3)

In [9]:
Y.size

12

In [11]:
x = np.array(['hello', 'world'])

In [12]:
print(x)

['hello' 'world']


In [14]:
print('shape', x.shape)
print('type', type(x))
print('dtype', x.dtype)

shape (2,)
type <class 'numpy.ndarray'>
dtype <U5


In [15]:
x = np.array([1,2,3,4,.5], dtype=np.int64)
print(x)
print('dtype', x.dtype)

[1 2 3 4 0]
dtype int64


In [19]:
x = np.array([1,2,3,4,5])
np.save("my_array", x)

In [21]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]
