# Using zeroes, ones, and full to build arrays

In [1]:
import numpy as np

In [4]:
x = np.zeros((3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
x = np.full((4,4,4), "foobar")
y = np.full((2,2,2), 1, dtype=int)
print("x:\n", x, "\n\n Shape:", x.shape, "\n")
print("y:\n", y, "\n\n Shape:", y.shape, "\n")


x:
 [[['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']]

 [['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']]

 [['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']]

 [['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']
  ['foobar' 'foobar' 'foobar' 'foobar']]] 

 Shape: (4, 4, 4) 

y:
 [[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]] 

 Shape: (2, 2, 2) 



# Build a Matrix
As you will learn later, a fundamental array in Linear Algebra is the Identity Matrix. An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. The function np.eye(N) creates a square N x N ndarray corresponding to the Identity matrix. Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument.

In [41]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
x = np.diag([10,20,30,40,50])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


### one argument is zero start index 

In [50]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


### Two arguments are a range, the first is inclusive and the last is exclusive

In [54]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


### Three arguments are a range, the first is inclusive and the last is exclusive, separated by the third

In [58]:
x = np.arange(2, 10, 2)
print(x)

[2 4 6 8]


### If you care about floats then use this
Even though the np.arange() function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function np.linspace(). The np.linspace(start, stop, N) function returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and thestop values are included. We should also note the np.linspace() function needs to be called with at least two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values. Let's see some examples:

In [65]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [66]:
x = np.linspace(0, 25, 10, endpoint = False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


### Reshape a pre-existing np array 

In [68]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [79]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### You can chain methods

In [81]:
x = np.arange(20).reshape(10, 2)
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


### Random Arrays
The last type of ndarrays we are going to create are random ndarrays. Random ndarrays are arrays that contain random numbers. Often in Machine Learning, you need to create random matrices, for example, when initializing the weights of a Neural Network. NumPy offers a variety of random functions to help us create random ndarrays of any shape.

Let's start by using the np.random.random(shape) function to create an ndarray of the given shape with random floats in the half-open interval [0.0, 1.0).

In [84]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.95969681 0.05416708 0.95928723]
 [0.71816923 0.01078249 0.02662418]
 [0.17780648 0.51053221 0.51594894]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


NumPy also allows us to create ndarrays with random integers within a particular interval. The function np.random.randint(start, stop, size = shape) creates an ndarray of the given shape with random integers in the half-open interval [start, stop). Let's see an example:

In [89]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,8,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[7 7]
 [6 5]
 [7 5]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties. For example, you may want the random numbers in the ndarray to have an average of 0. NumPy allows you create random ndarrays with numbers drawn from various probability distributions. The function np.random.normal(mean, standard deviation, size=shape), for example, creates an ndarray with the given shape that contains random numbers picked from a normal (Gaussian) distribution with the given mean and standard deviation. Let's create a 1,000 x 1,000 ndarray of random floating point numbers drawn from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.

In [90]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[-0.18414096  0.07369984  0.0878327  ...  0.07774092  0.20788756
   0.0101602 ]
 [ 0.07575319  0.1722052  -0.0560019  ...  0.0179649   0.07947743
  -0.11553234]
 [-0.05936082  0.089443   -0.02274669 ...  0.16212614 -0.06398488
  -0.03950958]
 ...
 [-0.13132294 -0.03851307 -0.02774065 ...  0.13771298  0.15528724
  -0.03869296]
 [ 0.02548354 -0.26228955  0.22897113 ...  0.05989987 -0.13132468
  -0.06492004]
 [ 0.01218644 -0.13886956  0.07792867 ...  0.00599855  0.06853118
  -0.01373386]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 5.399094447484975e-05
The maximum value in X is: 0.4756808822130646
The minimum value in X is: -0.4822302300169359
X has 499557 negative numbers
X has 500443 positive numbers
